version: '3.3'
services:
    db:
        image: mongo
        ports:
            - 27010:27017
        restart: always
        volumes:
            - /root/pet-project-backup/backups:/backups
        container_name: pet-project-mongo-db
    redis:
        image: redis
        ports:
            - 6377:6379
        restart: always
        container_name: pet-project-redis
    petProjectContainer:
        image: pet-project-server
        restart: always
        ports:
            - 5000:5000
        container_name: petProjectContainer
